version: 2.1

workflows:
  default:
    filter:
      branches:
          only: master
  jobs:
    build:
        executor: default
        steps:
            - checkout
            - run: dotnet test

executors:
  default:
    docker:
    - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ControllizerDeckProject/
    

            #- run: 
            #    name: Restore pkgs
            #    command: dotnet restore
            #- run:
            #    name: Build
            #    command: dotnet build
            #- run:
            #    name: Test
            #   command: dotnet test 
