version: 2.1

executors:
  default:
    docker:
    - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    - persist_to_workspace:
        root: /test_results
    
jobs:
    build:
        executor: default
        steps:
            - checkout
            - run: dotnet test ControllizerDeckProject/ControllizerDeckProject.sln
            #- run: 
            #    command: mkdir -p test-results
            - store_test_results:
                path: test-results
workflows:
  default:
    jobs:
      - build:
        filter:
          branches:
              only: master
