version: 2.1

executors:
  default:
    docker:
    - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: ControllizerDeckProject/
    
jobs:
    build:
        executor: default
        steps:
            - checkout
            - run: dotnet test ControllizerCoreTests/ControllizerCoreTests.csproj
            #- run: 
            #    name: Restore pkgs
            #    command: dotnet restore
            #- run:
            #    name: Build
            #    command: dotnet build
            #- run:
            #    name: Test
            #   command: dotnet test 
            
workflows:
  default:
    jobs:
      - build:
        filter:
          branches:
              only: master
